### ISSUE TITLE
Review/Upgrade Grid component

### ISSUE THREAD

**Issue by lorenzogm** [valtech-ch/ring#13]
The component is created but it should be reviewed.

**Comment by tamsler-valtech** [comment]
**Grid Model:**
- Spacing will be applied to row #2 and higher as `mt-${spacing}`and to col #2 and higher as `ml-${spacing}`

**Grid Item**
- Doesn't need title
- xl is missing
- add property for padding default to 0, could be applied with `pa-${padding}`

**Comment by lorenzogm** [comment]
@tamsler-valtech 

1. Spacing: It's the one defined in Material UI
2. xl should be added
3. Probably we want to add margins and spacing for both Grid and Grid Item, maybe a json field?
