### ISSUE TITLE
Update the types with a webhook in Contentful

### ISSUE THREAD

**Issue by lorenzogm** [valtech-ch/ring#44]
1. Create a webhook in Contenful: When content model is published/unpublished/deleted trigger a github action (https://nharox.com/blog/trigger-github-actions-with-contentful-webhook/)
- Use the payload to send useful information like the content model ID

2. Update the types with the `nx types ring` command.
- Is it possible to trigger the the types script to update only the content model ID?

3. Commit the changes and create a PR: https://github.com/marketplace/actions/create-pull-request
- Is it possible to create only one PR per content model? If there is a PR for the same content model, it should update the PR, not create a new one

**Comment by FlorinSenoner** [comment]
Like the idea 👍 
Was thinking if that flow has any downsides, like introducing breaking changes into the build (i.e. TS errors), but think it might actually be even better if it breaks the build right away.
